name: Trigger auto deployment for wsp-app-cont

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/wsp-app-cont-AutoDeployTrigger-8056a24f-8083-45d9-aee0-57a83eeffb49.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WSPAPPCONT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: xanelreg.azurecr.io
          registryUsername: ${{ secrets.WSPAPPCONT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WSPAPPCONT_REGISTRY_PASSWORD }}
          containerAppName: wsp-app-cont
          resourceGroup: xanel
          imageToBuild: xanelreg.azurecr.io/wsp-app-cont:${{ github.sha }}
          

     

